import { Syne } from "next/font/google";
import "./globals.css";
import BackgroundGrid from "./components/BackgroundLines";

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${syne.variable} antialiased font-sans`}
      >
        <BackgroundGrid>
          {children}
        </BackgroundGrid>
        
      </body>
    </html>
  );
}
